### ISSUE TITLE
Fazer heatmap de disponibilidade da equipe

### ISSUE THREAD

**Issue by Eric-chagas** [Requisitos-de-Software/2022.2-Spotify#3]
- [x] Heatmap de disponibilidade de cada integrante da equipe em planilha.

**Comment by raphaiela** [comment]
https://docs.google.com/spreadsheets/d/1a9nKDxPT5SD1lJ8n_hUy3w3P7JKWb3GttH7Y0JvhIVU/edit?usp=sharing
